name: main
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
    - name: clone target
      uses: actions/checkout@v2
      with:
        path: target
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}
    - name: clone runbooks
      uses: actions/checkout@v2
      with:
        path: runbooks
        repository: deadsnakes/runbooks
    - name: pull upstream
      run: runbooks/import-upstream --repo target ${{ github.event.inputs.version }}
  build:
    name: build
    needs: update
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: bionic
        - name: focal
        - name: jammy
    env:
      DEBEMAIL: 'asottile+deadsnakes@umich.edu'
      DEBFULLNAME: 'Anthony Sottile (deadsnakes)'
      GIT_AUTHOR_NAME: 'Anthony Sottile'
      GIT_AUTHOR_EMAIL: 'asottile+deadsnakes@umich.edu'
      GIT_COMMITTER_NAME: 'Anthony Sottile'
      GIT_COMMITTER_EMAIL: 'asottile+deadsnakes@umich.edu'
    steps:
    - name: clone target
      uses: actions/checkout@v2
      with:
        path: target
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}
    - name: clone runbooks
      uses: actions/checkout@v2
      with:
        path: runbooks
        repository: deadsnakes/runbooks
    - uses: actions/setup-python@v2
    - name: install gbp
      run: pip install gbp==0.9.24
    - name: install devscripts
      run: sudo apt-get update -qq && sudo apt-get install -y devscripts
    - name: import gpg key
      run: |
        install --directory ~/.gnupg --mode 700
        base64 -d <<< '${{ secrets.GPG_PUBLIC }}' > ~/.gnupg/pubring.gpg
        base64 -d <<< '${{ secrets.GPG_SECRET }}' > ~/.gnupg/secring.gpg
        chmod 600 ~/.gnupg/*
    - name: update branch
      run: SHELL=false runbooks/refresh-patches --repo target ubuntu/${{ matrix.name }}
    - name: build
      run: mkdir dist && cd target && ../runbooks/build
    - name: test
      run: runbooks/quick-test --distrib-codename ${{ matrix.name }} --dist-dir dist --src-dir target
    - name: release
      run: cd target && ../runbooks/release
